// src/components/landing/Showcase.tsx
const SAMPLE_IMAGES = [
  {
    url: "https://pub-338b29cd5690487d94d8748dd2c8bf43.r2.dev/generated/322f050d-205d-446f-b249-ebd164403753.webp",
    prompt: "Demon Slayer Corps assembled beneath a blood moon",
  },
  {
    url: "https://pub-338b29cd5690487d94d8748dd2c8bf43.r2.dev/generated/41840572-c8bb-4355-8d10-3ca208af487a.webp",
    prompt: "Matte black Land Rover Defender at sunrise",
  },
  {
    url: "https://pub-338b29cd5690487d94d8748dd2c8bf43.r2.dev/generated/68df694-d5d8-4aa1-8c6d-2b9c13005ea3.png",
    prompt: "Ethnic fashion editorial portrait",
  },
  {
    url: "https://pub-338b29cd5690487d94d8748dd2c8bf43.r2.dev/generated/068df694-d5d8-4aa1-8c6d-2b9c13005ea3.webp",
    prompt: "Red Formula 1 car on the Monaco circuit",
  },
  {
    url: "https://pub-338b29cd5690487d94d8748dd2c8bf43.r2.dev/generated/15c43f07-e574-43eb-a27b-b98b3da624e1.webp",
    prompt: "crystal dragon soaring above floating islands",
  },
  {
    url: "https://pub-338b29cd5690487d94d8748dd2c8bf43.r2.dev/generated/5c053b49-7d1c-4ec2-950b-f36978d8201f.png",
    prompt: "A hyper-realistic close-up portrait of an ancient mechanical owl",
  },
];
const Showcase = () => {
  return (
    <div id="examples" className="max-w-5xl mx-auto px-6 py-20">
      <div className="text-center mb-12">
        <h2 className="text-4xl sm:text-5xl font-semibold mb-3 tracking-tight">
          See what&apos;s possible
        </h2>
        <p className="text-gray-500 text-base">
          Real images generated by LumiForge AI
        </p>
      </div>

      <div className="grid grid-cols-3 gap-6">
        {SAMPLE_IMAGES.map((img, i) => (
          <div
            key={i}
            className="rounded-2xl overflow-hidden border shadow-sm aspect-square"
          >
            <img
              src={img.url}
              alt={img.prompt}
              className="w-full h-full object-cover hover:scale-105 transition-transform duration-300"
            />
          </div>
        ))}
      </div>
    </div>
  );
};

export default Showcase;

